### ISSUE TITLE
System shortcuts don't work on macOS Monterey

### ISSUE THREAD

**Issue by 98o718** [ThijmenDam/BarTranslate#29]
Hello! Thanks for the great app!

System shortcuts such as CMD+C or CMD+A don't work

I have M1 MacBook on 12.6 macOS

**Comment by ThijmenDam** [comment]
Hi @98o718, I am aware of this issue, however I'm do not know what the culprit is (yet). 

On my personal MacBook (2016, Intel, Monterey) the shortcuts do _not_ work. However, on my work MacBook (2020, M1, Ventura & Sonoma) the shortcuts _do_ work. So perhaps the issue only occurs on Monterey, considering this is the version you run as well. 

In your case, updating to Sonoma might solve the issue.

**Comment by ThijmenDam** [comment]
Fixed in https://github.com/ThijmenDam/BarTranslate/releases/tag/v1.0.1.
